"""Finding / envelope / grade tests — the shared contract with pipeline-check."""
from __future__ import annotations

import io
import json

from rich.console import Console

from pipeline_watch.output.formatter import report_json, report_terminal
from pipeline_watch.output.schema import (
    JSON_SCHEMA_VERSION,
    TOOL_NAME,
    Finding,
    Module,
    Severity,
    findings_envelope,
    score_from_findings,
    validate_finding_dict,
)


def _make(sev: Severity, **overrides) -> Finding:
    base = dict(
        module=Module.SUPPLY_CHAIN,
        severity=sev,
        signal="A new maintainer published a release.",
        baseline="Only 'alice' has published for requests in the last 3 years.",
        remediation="Freeze the dependency and review the maintainer addition upstream.",
        evidence={"package": "requests", "maintainer": "mallory"},
        timestamp="2026-04-20T12:00:00+00:00",
        check_id="SC-001",
    )
    base.update(overrides)
    return Finding(**base)


def test_finding_to_dict_contains_all_documented_fields() -> None:
    f = _make(Severity.HIGH)
    d = f.to_dict()
    assert d["tool"] == TOOL_NAME
    assert d["module"] == "supply-chain"
    assert d["severity"] == "HIGH"
    assert d["score"] == "D"
    assert d["signal"].startswith("A new maintainer")
    assert d["baseline"].startswith("Only 'alice'")
    assert d["evidence"] == {"package": "requests", "maintainer": "mallory"}
    assert d["remediation"].startswith("Freeze")
    assert d["timestamp"] == "2026-04-20T12:00:00+00:00"
    assert d["check_id"] == "SC-001"


def test_finding_defaults_timestamp_when_missing() -> None:
    f = Finding(
        module=Module.SUPPLY_CHAIN,
        severity=Severity.LOW,
        signal="x", baseline="y", remediation="z",
        evidence={}, timestamp="",
    )
    assert f.timestamp  # non-empty, autogenerated


def test_grade_mapping_for_single_finding_severity() -> None:
    assert _make(Severity.LOW).to_dict()["score"] == "B"
    assert _make(Severity.MEDIUM).to_dict()["score"] == "C"
    assert _make(Severity.HIGH).to_dict()["score"] == "D"
    assert _make(Severity.CRITICAL).to_dict()["score"] == "D"


def test_aggregate_grade_a_when_no_findings() -> None:
    s = score_from_findings([])
    assert s["grade"] == "A"
    assert s["total"] == 0


def test_aggregate_grade_b_only_low() -> None:
    s = score_from_findings([_make(Severity.LOW)])
    assert s["grade"] == "B"


def test_aggregate_grade_c_medium_or_multiple_low() -> None:
    assert score_from_findings([_make(Severity.MEDIUM)])["grade"] == "C"
    assert score_from_findings([_make(Severity.LOW), _make(Severity.LOW)])["grade"] == "C"


def test_aggregate_grade_d_high_or_critical() -> None:
    assert score_from_findings([_make(Severity.HIGH)])["grade"] == "D"
    assert score_from_findings([_make(Severity.CRITICAL)])["grade"] == "D"
    # Mixed: any HIGH/CRITICAL drops the whole grade to D.
    assert score_from_findings([
        _make(Severity.LOW), _make(Severity.HIGH),
    ])["grade"] == "D"


def test_envelope_fields() -> None:
    env = findings_envelope(
        [_make(Severity.HIGH)], tool_version="0.1.0", module="supply-chain",
    )
    assert env["schema_version"] == JSON_SCHEMA_VERSION
    assert env["tool"] == TOOL_NAME
    assert env["tool_version"] == "0.1.0"
    assert env["module"] == "supply-chain"
    assert env["score"]["grade"] == "D"
    assert len(env["findings"]) == 1


def test_validate_finding_dict_accepts_valid() -> None:
    d = _make(Severity.HIGH).to_dict()
    assert validate_finding_dict(d) == []


def test_validate_finding_dict_rejects_missing_fields() -> None:
    errors = validate_finding_dict({"tool": TOOL_NAME})
    assert any("missing field" in e for e in errors)


def test_validate_finding_dict_accepts_pipeline_check_tool() -> None:
    # The shared schema: a pipeline-check finding also validates.
    d = _make(Severity.HIGH).to_dict()
    d["tool"] = "pipeline-check"
    assert validate_finding_dict(d) == []


def test_validate_finding_dict_rejects_bad_severity_and_module() -> None:
    d = _make(Severity.HIGH).to_dict()
    d["severity"] = "CATASTROPHIC"
    d["module"] = "bogus"
    errors = validate_finding_dict(d)
    assert any("invalid severity" in e for e in errors)
    assert any("invalid module" in e for e in errors)


def test_report_json_produces_valid_json() -> None:
    text = report_json(
        [_make(Severity.HIGH), _make(Severity.LOW)],
        tool_version="0.1.0",
        module="supply-chain",
    )
    payload = json.loads(text)
    assert payload["schema_version"] == JSON_SCHEMA_VERSION
    assert payload["score"]["grade"] == "D"
    assert len(payload["findings"]) == 2
    # Field ordering in the first finding follows the documented schema so
    # diffs of the output file remain readable.
    keys = list(payload["findings"][0].keys())
    assert keys[:4] == ["tool", "module", "severity", "score"]


def test_report_terminal_runs_without_errors() -> None:
    buf = io.StringIO()
    console = Console(file=buf, force_terminal=False, width=120)
    findings = [_make(Severity.HIGH), _make(Severity.LOW)]
    report_terminal(findings, score_from_findings(findings), console=console)
    out = buf.getvalue()
    # Grade letter and panel title both appear.
    assert "Grade D" in out
    assert "pipeline-watch" in out
    # Each check_id is rendered in the table.
    assert "SC-001" in out


def test_report_terminal_no_findings() -> None:
    buf = io.StringIO()
    console = Console(file=buf, force_terminal=False, width=120)
    report_terminal([], score_from_findings([]), console=console)
    out = buf.getvalue()
    assert "Grade A" in out
    assert "No behavioural deviations" in out
